// What's left here after the DXCC entity table moved to cty.json: the continent enum, and the
// handful of places where a callsign says something about the station that no prefix table carries.
// Everything that maps a callsign to an entity now lives in ./cty.ts, generated by scripts/cty.ts.

export const continents = {
    NA: "North America",
    SA: "South America",
    EU: "Europe",
    AF: "Africa",
    OC: "Oceania",
    AS: "Asia",
    AN: "Antartica",
};
export type Continent = keyof typeof continents;

/**
 * Primary administrative subdivisions a callsign gives away on its own, keyed by DXCC entity.
 *
 * cty.dat stops at the entity, and for most of the world that's as far as a callsign goes: a US or
 * Canadian call area moved with its operator decades ago, so W6 says nothing about California. VK
 * numbers are still tied to the state, and the UN HQ station is in New York because the building is.
 */
export const stateRegexps: Record<number, Record<string, RegExp>> = {
    // Australia
    150: {
        ACT: /^[^0-9]{2}1.*/,
        NSW: /^[^0-9]{2}2.*/,
        VIC: /^[^0-9]{2}3.*/,
        QLD: /^[^0-9]{2}4.*/,
        SA: /^[^0-9]{2}5.*/,
        WA: /^[^0-9]{2}6.*/,
        TAS: /^[^0-9]{2}7.*/,
        NT: /^[^0-9]{2}8.*/,
    },
    // United Nations HQ
    289: {
        NY: /.*/,
    },
};
